# Generated by Django 2.0.1 on 2018-02-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20180131_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='vendor_visible',
            field=models.BooleanField(default=True),
        ),
    ]
