# Generated by Django 2.0.1 on 2018-02-09 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_event_potential_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='rsvp.Question'),
            preserve_default=False,
        ),
    ]
