# Generated by Django 2.0.1 on 2018-02-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_response_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event'),
            preserve_default=False,
        ),
    ]
