# Generated by Django 2.0.1 on 2018-02-09 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_remove_response_event'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='response',
        #     name='event',
        #     field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event'),
        #     preserve_default=False,
        # ),
    ]
