# Generated by Django 2.0.1 on 2018-02-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_response_event'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='response',
    #         name='event',
    #     ),
    # ]
