# Generated by Django 2.0.1 on 2018-02-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0010_remove_response_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
        # migrations.RemoveField(
        #     model_name='response',
        #     name='event',
        # ),
    ]
