# Generated by Django 2.0.1 on 2018-02-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0012_response_freetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='response_freetext',
            name='question_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
