# Generated by Django 2.0.1 on 2018-02-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0014_auto_20180211_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsefreetext',
            name='user',
        ),
        # migrations.RemoveField(
        #     model_name='response',
        #     name='event',
        # ),
        migrations.AddField(
            model_name='question',
            name='freetext',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ResponseFreetext',
        ),
    ]
